{% set version = "23.0.5" %}
{% set sha256 = "b71026ab12cfab4e13e016e61fe20258a7dc798a3e90d67d12368ae4d87335d4" %}

package:
  name: galaxy-util
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/galaxy-util/galaxy-util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bleach
    - boltons
    - docutils
    - importlib_resources
    - packaging <22
    - pyparsing
    - python >=3.7
    - pyyaml
    - requests
    - routes
    - typing_extensions
    - zipstream-new
    # extras_require:
    #- dictobj
    - future
    - cheetah3
  run_constrained:
    # Disallow installation of conflicting older package.
    - galaxy-lib <0a0

test:
  imports:
    - galaxy
    - galaxy.exceptions
    - galaxy.util
    - galaxy.util.custom_logging
    - galaxy.util.path
    - galaxy.util.tool_shed

about:
  home: https://galaxyproject.org
  license: AFL-3.0
  license_file: LICENSE
  summary: Galaxy Generic Utilities
  doc_url: https://docs.galaxyproject.org
  dev_url: https://github.com/galaxyproject/galaxy

extra:
  recipe-maintainers:
    - nsoranzo
    - bgruening
