{% set version = "22.1.1" %}
{% set sha256 = "70c1b79f2d2da64a7402f0dee70b4e4975ce49e14d6fa3a66d2e36f5ceb2bacf" %}

package:
  name: galaxy-util
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/galaxy-util/galaxy-util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bleach
    - boltons
    - docutils
    - markupsafe
    - packaging
    - python >=3.6
    - pyyaml
    - requests
    - routes
    #- dictobj
    - future
    - cheetah3
    - pycryptodome
    - zipstream-new
  run_constrained:
    # Disallow installation of conflicting older package.
    - galaxy-lib <0a0

test:
  imports:
    - galaxy
    - galaxy.exceptions
    - galaxy.util
    - galaxy.util.custom_logging
    - galaxy.util.path

about:
  home: https://galaxyproject.org
  license: AFL-3.0
  license_file: LICENSE
  summary: Galaxy Generic Utilities
  doc_url: https://docs.galaxyproject.org
  dev_url: https://github.com/galaxyproject/galaxy

extra:
  recipe-maintainers:
    - nsoranzo
    - bgruening
